### ISSUE TITLE
Python 3 required

### ISSUE THREAD

**Issue by arcanelab** [hauzer/scrobbler#4]
Hi! I'm running OSX 10.11.6. I have Python 3 installed via Homebrew, but after running scrobbler it still complains Python 3 is required. Any ideas how to tackle this issue? I'm a complete noob when it comes to Python. Thanks in advance!

**Comment by hauzer** [comment]
Hello. Not much experience with OS X, but maybe I can help. From what I've gathered, the `python` command is exclusively reserved for Python 2 in OS X. There should be other commands, like `python3` and `python33`, which point to more specific versions of Python. I suspect `scrobbler` is in `PATH`. The following should, then, work: ``python3 `which scrobbler` ``.

**Comment by arcanelab** [comment]
Thanks for your response, Hauzer! The method you recommended was one of the few things I'd already tried before opening this issue, but it also gave me an error:
```
Traceback (most recent call last):
  File "/usr/local/bin/scrobbler", line 5, in <module>
    from pkg_resources import load_entry_point
  File "/usr/local/lib/python3.6/site-packages/pkg_resources/__init__.py", line 3019, in <module>
    @_call_aside
  File "/usr/local/lib/python3.6/site-packages/pkg_resources/__init__.py", line 3003, in _call_aside
    f(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/pkg_resources/__init__.py", line 3032, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/usr/local/lib/python3.6/site-packages/pkg_resources/__init__.py", line 655, in _build_master
    ws.require(__requires__)
  File "/usr/local/lib/python3.6/site-packages/pkg_resources/__init__.py", line 963, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/usr/local/lib/python3.6/site-packages/pkg_resources/__init__.py", line 849, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'scrobblerh==1.1.3-1' distribution was not found and is required by the application
```
As I said, unfortunately I don't have Python experience yet (I plan to learn it in the future, though), so I cannot really make sense of this error message. Perhaps it is some kind of dependency issue?

**Comment by hauzer** [comment]
Oh, forgot an important detail. You should first install `scrobblerh` inside of the Python 3 distribution by executing `python3 -m pip install scrobblerh`. It will perhaps even overwrite the `scrobbler` script inside of wherever the default Python 2 distribution put them, meaning a simple `scrobbler` call will now work.

**Comment by arcanelab** [comment]
Excellent, with that ``` python3 `which scrobbler` ``` started working. Thank you so much, I really appreciate your help.
