### ISSUE TITLE
syntax error

### ISSUE THREAD

**Issue by realmonado** [hauzer/scrobbler#7]
```
Traceback (most recent call last):
  File "/usr/bin/scrobbler", line 33, in <module>
    sys.exit(load_entry_point('scrobblerh==1.1.4', 'console_scripts', 'scrobbler')())
  File "/usr/bin/scrobbler", line 25, in importlib_load_entry_point
    return next(matches).load()
  File "/usr/lib/python3.9/importlib/metadata.py", line 77, in load
    module = import_module(match.group('module'))
  File "/usr/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 972, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 786, in exec_module
  File "<frozen importlib._bootstrap_external>", line 923, in get_code
  File "<frozen importlib._bootstrap_external>", line 853, in source_to_code
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/usr/lib/python3.9/site-packages/scrobbler.py", line 331
    print flush()
          ^
SyntaxError: invalid syntax
```

updated pip and python, installed via pip on void linux. 
invoked by running `scrobbler`

**Comment by hauzer** [comment]
Just tested on WSL Ubuntu. Works fine.
![image](https://user-images.githubusercontent.com/2883385/107807398-5bda6d80-6d68-11eb-8359-69d9d966c897.png)

Must be something wonky with the packaging system of the distro. Try removing the package and reinstalling it with the `--user` flag.

**Comment by hauzer** [comment]
Also, try installing the package in a venv and see if it works.

**Comment by realmonado** [comment]
installing in a venv fixed the issue, outside of it i get this error:
```
Traceback (most recent call last):
  File "/usr/bin/scrobbler", line 33, in <module>
    sys.exit(load_entry_point('scrobblerh==1.1.4', 'console_scripts', 'scrobbler')())
  File "/usr/bin/scrobbler", line 25, in importlib_load_entry_point
    return next(matches).load()
  File "/usr/lib/python3.9/importlib/metadata.py", line 77, in load
    module = import_module(match.group('module'))
  File "/usr/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 790, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/usr/lib/python3.9/site-packages/scrobbler/scrobbler.py", line 50, in <module>
    from lastfm import lfm
  File "/usr/lib/python3.9/site-packages/lfmh-1.1.1-py3.9.egg/lastfm/lfm.py", line 25, in <module>
    import  requests
  File "/usr/lib/python3.9/site-packages/requests/__init__.py", line 87, in <module>
    check_compatibility(urllib3.__version__, chardet.__version__)
AttributeError: module 'chardet' has no attribute '__version__'
``

**Comment by hauzer** [comment]
This tells me that maybe system-wide urllib3/chardet/requests/other dependencies are too outdated for scrobbler. You got the latest versions of them when you installed in a venv, that's why it works. Not sure how Void Linux manages Python packages, but try updating them if you can (at least the relevant ones: `requests`, `urllib3`, `chardet`, etc.). I should probably put version constraints for `requests` in `lfm`. I have no idea which minimal version would work, to be honest. But again, I don't think this is the real problem, because `requests` seems to be working okay, but `chardet` looks severely outdated.

Try updating and see if it works.

**Comment by realmonado** [comment]
updated the packages with pip and they work. thank you very much for writing this piece of software and helping :)

**Comment by hauzer** [comment]
No problem, glad it worked out. 🙂
